// <auto-generated />
using System;
using ConsoleApp4.Dal.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp4.Migrations
{
    [DbContext(typeof(ApplicationDBcontext))]
    partial class ApplicationDBcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp4.Dal.Entity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeptId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.HasIndex("EmployeeProjectId");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("ConsoleApp4.Dal.Entity.EmployeeProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmployeeProject");
                });

            modelBuilder.Entity("ConsoleApp4.Dal.Entity.department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("ConsoleApp4.Dal.Entity.project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeProjectId");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("ConsoleApp4.Dal.Entity.Employee", b =>
                {
                    b.HasOne("ConsoleApp4.Dal.Entity.department", "department")
                        .WithMany("Emps")
                        .HasForeignKey("DeptId");

                    b.HasOne("ConsoleApp4.Dal.Entity.EmployeeProject", "EmployeeProject")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeProjectId");

                    b.Navigation("EmployeeProject");

                    b.Navigation("department");
                });

            modelBuilder.Entity("ConsoleApp4.Dal.Entity.project", b =>
                {
                    b.HasOne("ConsoleApp4.Dal.Entity.Employee", null)
                        .WithMany("projects")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("ConsoleApp4.Dal.Entity.EmployeeProject", "EmployeeProject")
                        .WithMany("projects")
                        .HasForeignKey("EmployeeProjectId");

                    b.Navigation("EmployeeProject");
                });

            modelBuilder.Entity("ConsoleApp4.Dal.Entity.Employee", b =>
                {
                    b.Navigation("projects");
                });

            modelBuilder.Entity("ConsoleApp4.Dal.Entity.EmployeeProject", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("projects");
                });

            modelBuilder.Entity("ConsoleApp4.Dal.Entity.department", b =>
                {
                    b.Navigation("Emps");
                });
#pragma warning restore 612, 618
        }
    }
}
